### DISCUSSION TITLE
how to use self-signed tls certificate when connecting to local relay server

### DISCUSSION THREAD

**Discussion by Sherlock-Holo** [n0-computer/iroh#3347] [Q&A]
I notice iroh-relay support specify custom tls certificate by

```toml
[tls]
cert_mode = "Manual"
manual_cert_path = "/path/to/certs/cert.pem"
manual_key_path = "/path/to/certs/cert.key.pem"
```

however, when we use custom relay [RelayMode::Custom](https://docs.rs/iroh/latest/iroh/endpoint/enum.RelayMode.html#variant.Custom), I only can use [RelayNode](https://docs.rs/iroh/latest/iroh/struct.RelayNode.html) to create a RelayMap, but it doesn't give me any chance to specify a ca certificate, allow me to connect a self-signed iron relay server

without self-signed tls certificate support, it's hard for me to try to learn and figure out if I can use iroh in my project
