### ISSUE TITLE
--config iroh and --config iroh console expects diffrent format

### ISSUE THREAD

**Issue by s2dd** [n0-computer/iroh#1930]
#in /iroh/iroh

RUN IROH
#iroh.config.toml
[derp_nodes]
url = "http://0.0.0.0:3340"
stun_only = false
stun_port = 3478

`cargo r -- --config <path>/iroh.config.toml start`   
Error: invalid type: map, expected a sequence

--change conf to [[derp-nodes]] works for iroh

RUN IROH CONSOLE
#iroh.config.toml
[[derp_nodes]]
url = "http://0.0.0.0:3340"
stun_only = false
stun_port = 3478

`cargo r --config <path>/iroh.config.toml console` 
error: failed to load config from `<path>/iroh.config.toml`

Caused by:
  failed to load TOML configuration from `<path>/iroh.config.toml`

Caused by:
  failed to parse key `derp_nodes`

Caused by:
  expected string but found table in list

--change back to [derp-nodes] works for iroh console

**Comment by ramfox** [comment]
Going to add some context here.

The `iroh console` command does not expect the same config format as any other iroh command.

When running `iroh` for all other commands it accepts a config formatted like this (focused on the `derp_nodes` field):
```toml
#iroh.config.toml
[[derp_nodes]]
url = "http://0.0.0.0:3340/"
stun_only = false
stun_port = 3478
```

But `iroh console` expects a config that looks like this:
```toml
#iroh.config.toml
[derp_nodes]
url = "http://0.0.0.0:3340/"
stun_only = false
stun_port = 3478
```
