### ISSUE TITLE
Since V0.19.0, it seems that the relay is unable to detect public IPv4 addresses.

### ISSUE THREAD

**Issue by zh522130** [n0-computer/iroh#2490]
I recently updated the relay to `v0.20.0` and noticed that the `CallMeMaybe` list printed in the client logs does not include the server's public IPv4 address, only the LAN IP and public IPv6. I also tested `v0.18.0` and `v0.19.0`, as well as the default `NA_RELAY_HOSTNAME` and `EU_RELAY_HOSTNAME`. Apart from the `CallMeMaybe` list of my self-built v0.18.0 relay, which includes the public IPv4 address, the `CallMeMaybe` lists of other versions and the current default relays do not include the public IPv4 address.

**Comment by ramfox** [comment]
Unfortunately, I can't reproduce this. My `CallMeMaybe` messages are including a public IPv4 address on v0.20.0

If you have the iroh cli installed, can you try running `iroh doctor report` to see if the netcheck report includes a public ipv4 address?

**Comment by zh522130** [comment]
> Unfortunately, I can't reproduce this. My `CallMeMaybe` messages are including a public IPv4 address on v0.20.0
> 
> If you have the iroh cli installed, can you try running `iroh doctor report` to see if the netcheck report includes a public ipv4 address?

The `iroh doctor report` does show the public IPv4 address. Upon re-examining the code, I found that the default relay indeed reports the public IPv4 address. The previous tests did not report IPv4 because my `stun_port` was set incorrectly. It seems there might be an issue with my relay configuration. My current configuration file for the latest relay is as follows:

```toml
secret_key = "tkqwqqxqnyaxmq6mtqccajacqguczyy2cxd4ernc45j6j74rjbaa"
http_bind_addr = "[::]:12345"
stun_port = 13478
enable_stun = true
enable_relay = true

[tls]
hostname = "relay.example.com"
https_bind_addr = "[::]:12346"
cert_mode = "Manual"
prod_tls = true
manual_cert_path = "/home/test/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/relay.example.com/relay.example.com.crt"
manual_key_path = "/home/test/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/relay.example.com/relay.example.com.key"
```

Additionally, the server has opened UDP port 13478 and TCP port 12346.

 The relay configuration for v0.18.0 is as follows:

```toml
secret_key = "tkqwqqxqnyaxmq6mtqccajacqguczyy2cxd4ernc45j6j74rjbaa"
addr = "[::]:12346"
stun_port = 13478
hostname = "relay.example.com"
enable_stun = true
enable_relay = true

[tls]
cert_mode = "Manual"
prod_tls = true
contact = "test@test.com"
cert_dir = "/home/test/.local/share/caddy/certificates/acme-v02.api.letsencrypt.org-directory/relay.example.com/"
captive_portal_port = 12347
```

The same ports are open. Are my latest configuration file and port openings correct?
